version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "athenaquery"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xutjbkh54z4k"
s3_prefix = "athenaquery"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

